[tool.poetry]
name = "python-project-50"
version = "0.1.0"
description = ""
authors = ["ilya-ship-it <tulupov.2712@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
